name: Build Sorting Hat Executable

on:
  push:
    branches: [ main ]
    paths:
      # Trigger on changes to any Python file, assets, or configs
      - '**.py'
      - '**.gif'
      - '**.json'
      - '**.mp3'
      - '**.png'
      - 'requirements.txt'
      - '.github/workflows/main.yml'
  # Allow manual triggering from the Actions tab
  workflow_dispatch:

jobs:
  build-windows:
    name: Build for Windows
    runs-on: windows-latest

    steps:
      # --- Step 1: Get the code ---
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Step 2: Set up a clean Python environment ---
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          # THE CACHE IS INTENTIONALLY DISABLED to prevent a corrupted state.
          # This guarantees a clean, reproducible build every time.

      # --- Step 3: Install pinned Python dependencies ---
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        shell: pwsh

      # --- Step 4: Generate the base .spec file ---
      - name: Generate PyInstaller Spec File
        run: |
          pyi-makespec --onefile --windowed --name SortingHatApp `
            --add-data "hat.gif;." `
            --add-data "hat_think.gif;." `
            --add-data "settings.json;." `
            --add-data "sortinghat_music.mp3;." `
            --add-data "volume_on.png;." `
            --add-data "volume_off.png;." `
            sorting_hat_app.py
        shell: pwsh

      # --- Step 5: Modify .spec to Exclude pwdeep.py ---
      - name: Modify Spec File to Exclude Module
        run: |
          (Get-Content -Path SortingHatApp.spec) -replace "a = Analysis\(\['sorting_hat_app.py'\]", "a = Analysis(['sorting_hat_app.py'], excludes=['pwdeep']" | Set-Content -Path SortingHatApp.spec
        shell: pwsh

      # --- Step 6: Build the executable from the modified .spec file ---
      - name: Build executable from Spec File
        run: pyinstaller --noconfirm --clean SortingHatApp.spec
        shell: pwsh

      # --- Step 7: Prepare and Upload the Release Artifact ---
      - name: Prepare and Upload Release Artifact
        shell: pwsh
        run: |
          mkdir release
          copy dist\SortingHatApp.exe release\
          copy pwdeep.py release\
      - uses: actions/upload-artifact@v4
        with:
          name: SortingHat-Windows-Release
          path: release/